config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as:'guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"

    resources :courses do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resource :finishes, only: [:create, :destroy]
    end
    patch 'users/withdrawal', to: 'users#withdrawal'
    resources :users, only: [:show, :update,] do
      resource :relationships, only:[:create, :destroy]
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :destroy] do
      patch 'withdrawal', to:'users#withdrawal'
    end
    resources :courses, only: [:index, :show, :destroy]
    get '/', to: 'users#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_create :default_image_attach
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #各モデルとの関係性
  has_many :courses, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :finishes, dependent: :destroy
  has_one_attached :user_image

  #フォロワー機能のリレーション
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  #バリデーション
  validates :name, presence: true
  validates :introduction, length: { minimum: 2, maximum: 200 }, allow_blank: true
  validates :user_image, blob: { content_type: :image }

  def default_image_attach
    if !self.user_image.attached?
      self.user_image.attach(io: File.open(Rails.root.join('app/assets/images/no_image.png')), filename: 'no_image.png', content_type: 'image/png')
    end
  end

  def img_resize(width, height)
    self.user_image.variant(resize_to_limit: [width, height]).processed
  end

  #Relationshipモデル関係
  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following.include?(user)
  end
  
  #ゲストログイン用メソッド
  def self.guest
    find_or_create_by(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.introduction = "ゲストアカウントです。\n編集はできません。"
    end
  end
  
  def guest_match?
    self.name == "guestuser" && self.email == "guest@example.com"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @courses = @user.courses.page(params[:page]).per(5)
    @followed = @user.following.page(params[:page]).per(5)
    @followers = @user.followers.page(params[:page]).per(5)
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to admin_users_path
  end

  def withdrawal
    user = User.find(params[:user_id])
    if user.is_deleted
      user.update(is_deleted: false)
      flash[:notice] = "会員を有効にしました"
    else
      user.update(is_deleted: true)
      flash[:notice] = "会員を退会にしました"
    end
      redirect_to admin_user_path(user)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_course_table.html.erb
<div class="col-12 mt-2">
  <h5>投稿したコース</h5>
  <% if courses.present? %>
    <table class="table table-hover mt-3 table-striped bg-white border">
      <thead>
        <tr>
          <th class="text-center align-middle">ID</th>
          <th class="text-center align-middle">コースー名</th>
          <th class="text-center align-middle">登録住所</th>
          <th class="text-center align-middle">走りたい</th>
          <th class="text-center align-middle">走った</th>
        </tr>
      </thead>
      <tbody>
      <% courses.each do |course| %>
        <tr>
          <td class="text-center align-middle"><%= course.id %></td>
          <td class="align-middle pt-1 pb-0">
            <%= link_to admin_course_path(course), class:"d-inline-flex, text-muted" do %>
              <%= image_tag course.course_images[0].variant(
              gravity: "Center", resize: "35x35!", crop: "35x35+0+0").processed, class:"pr-1"%>
              <%= course.title %>
            <% end %>
          </td>
          <td class="text-center align-middle">
            <%= get_address(course.addresses) %>
            (<%= course.distance %> km)
          </td>
          <td class="text-center align-middle　text-muted"><%= course.favorites.count %></td>
          <td class="text-center align-middle"><%= course.finishes.count %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="text-center mx-auto mt-5">
      <%= paginate courses, theme: 'twitter-bootstrap-4' %>
    </div>
  <% else %>
    <h6 class="pl-3 pt-3 text-dark">投稿はありません。</h6>
  <% end %>
</div>

app/views/admin/users/_follow_table.erb
<% if users.present? %>
    <table class="table table-hover mt-4 table-striped bg-white border">
      <thead>
        <tr>
          <th class="text-center align-middle">ID</th>
          <th class="text-center align-middle">ユーザー名</th>
          <th class="text-center align-middle">フォロー数</th>
          <th class="text-center align-middle">フォロワー数</th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user| %>
          <tr>
            <td class="text-center align-middle"><%= user.id %></td>
              <td class="text-center align-middle pt-1 pb-0">
                <%= link_to admin_user_path(user) do %>
                  <%= image_tag user.user_image.variant(
                  gravity: "Center", resize: "35x35!", crop: "35x35+0+0").processed %>
                  <%= user.name %>
                <% end %>
              </td>
              <td class="text-center align-middle"><%= user.favorites.count %></td>
              <td class="text-center align-middle"><%= user.finishes.count %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  <% else %>
    <h5 class="pl-3 pt-3 text-muted">ユーザーはいません。</h5>
  <% end %>

app/views/admin/users/_followers.1.erb
<table class="table table-hover mt-4 table-striped bg-white border">
  <thead>
    <tr>
      <th>ユーザーID</th>
      <th>ユーザー名</th>
      <th>フォロー数</th>
      <th>フォロワー数</th>
    </tr>
  </thead>
  <tbody>
    <% user.followers.each do |user| %>
      <tr>
        <td><%= user.id %></td>
          <td>
            <%= link_to admin_user_path(user) do %>
              <%= image_tag user.user_image.variant(
              gravity: "Center", resize: "35x35!", crop: "35x35+0+0").processed%>
              <%= user.name %>
            <% end %>
          </td>
          <td><%= user.favorites.count %></td>
          <td><%= user.finishes.count %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-11 mx-auto">
    <h2>ユーザー一覧</h2>
    <table class="table table-hover mt-4 table-striped bg-white border mx-auto">
      <thead>
        <tr>
          <th class="text-center align-middle">ユーザーID</th>
          <th class="text-center align-middle">ユーザー名</th>
          <th class="text-center align-middle">e-mail</th>
          <th class="text-center align-middle">退会ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td class="text-center align-middle"><%= user.id %></td>
          <td class="align-middle pt-1 pb-0">
            <%= link_to admin_user_path(user), class:"text-muted" do %>
              <%= image_tag user.user_image.variant(
              gravity: "Center", resize: "35x35!", crop: "35x35+0+0").processed %>
              <%= user.name %>
            <% end %>
          </td>
          <td class="text-center align-middle"><%= user.email %></td>
          <td class="text-center align-middle text-muted">
            <%= user.is_deleted ? '退会済み' : '利用中' %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center mx-auto mt-5">
      <%= paginate @users, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="row">
  <div class="col-12 mx-auto">
    <div class="col-10 rounded mx-auto" id="user-title">
      <h1 class="text-white py-1 text-center">User Page</h1>
    </div>
    <div class="row mt-4 mx-auto">
      <div class="col-12 d-flex align-items-end">
        <div class="mr-2 mb-2" id="icon-area">
          <%= image_tag @user.user_image.variant(gravity: "Center", resize: "90x90!", crop: "90x90+0+0").processed,
          class:"user-icon", id:"default-icon" %>
        </div>
        <div id="profile_area" class="col-11 col-md-8 col-lg-8">
          <%= render 'public/users/info', user:@user %>
        </div>
        <div class="mt-2">
          <% if @user.is_deleted %>
          <div class="d-flex flex-column align-items-center">
            <div class=mb-2>
              <%= link_to  "有効にする", admin_user_withdrawal_path(@user), method: :patch,
              class:"btn btn-success btn-sm", "data-confirm" => "本当に消去しますか?" %>
            </div>
            <div>
              <%= link_to  "消去", admin_user_path(@user), method: :delete,
              class:"btn btn-danger btn-sm", "data-confirm" => "本当に消去しますか?" %>
            </div>
          </div>
          <% else %>
            <%= link_to  "退会にする", admin_user_withdrawal_path(@user), method: :patch,
            class:"btn btn-danger btn-sm", "data-confirm" => "退会にしますか" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-12 row mt-3">
      <%= render 'admin/users/course_table', courses:@courses %>
      <div class="col-12 mt-2">
        <ul class="nav nav-tabs" role="tablist">
          <li class="nav-item">
            <a class="nav-link nav-tag active text-dark" href="#follow" data-toggle="tab">
              フォロー</a>
          </li>
           <li class="nav-item">
            <a class="nav-link nav-tag text-dark" href="#follower" data-toggle="tab">
            フォロワー</a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane fade show active" id="follow">
            <%= render 'admin/users/follow_table', users: @followed %>
          </div>
          <div class="tab-pane fade" id="follower">
            <%= render 'admin/users/follow_table', users: @followers %>
          </div>
      </div>
    </div>
  </div>
</div>