config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as:'guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"

    resources :courses do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resource :finishes, only: [:create, :destroy]
    end
    patch 'users/withdrawal', to: 'users#withdrawal'
    resources :users, only: [:show, :update,] do
      resource :relationships, only:[:create, :destroy]
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :destroy] do
      patch 'withdrawal', to:'users#withdrawal'
    end
    resources :courses, only: [:index, :show, :destroy]
    get '/', to: 'users#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @courses = Course.page(params[:page])
  end

  def show
    @course = Course.find(params[:id])
  end
  
  def destroy
    Course.find(params[:id]).destroy
    redirect_to admin_courses_path
  end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/views/admin/courses/index.html.erb
<div class="row">
  <div class="col-12">
    <h2 class="ml-2">コース一覧</h2>
    <table class="table table-hover mt-4 table-striped bg-white border admin-table">
      <thead>
        <tr>
          <th class="text-center align-middle">ID</th>
          <th class="text-center align-middle">コース名</th>
          <th class="text-center align-middle">登録住所等</th>
          <th class="text-center align-middle">キーワード</th>
          <th class="text-center align-middle">ユーザー</th>
        </tr>
      </thead>
      <tbody>
        <% @courses.each do |course| %>
        <tr>
          <td class="text-center align-middle"><%= course.id %></td>
          <td class=" align-middle pt-1 pb-0">
            <%= link_to admin_course_path(course), class:"d-inline-flex text-muted" do %>
              <%= image_tag course.course_images[0].variant(
              gravity: "Center", resize: "35x35!", crop: "35x35+0+0").processed,
              class:"pr-1"%>
              <%= course.title %>
            <% end %>
          </td>
          <td class="text-center align-middle">
            <%= get_address(course.addresses) %>
            (<%= course.distance %> km)
          </td>
          <td class="text-center align-middle">
            <% course.entities.limit(4).each do |entity| %>
              <span class="key_word_tag shadow-sm"><%= entity.key_word %></span>
            <% end %>
          </td>
          <td class="text-center align-middle">
            <%= link_to admin_user_path(course.user), class:"text-muted" do %>
              <%= course.user.name %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center mx-auto mt-5">
      <%= paginate @courses, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>

app/views/admin/courses/show.html.erb
<div class="row">
  <div class="col-12 col-sm-12 col-md-12 col-lg-10 mx-auto">
    <div class="col-10 mx-auto mb-4" id="show-title">
      <h1 class=" text-white text-center pt-2 shadow-sm">コース詳細</h2>
    </div>
    <div class="swiper mx-auto">
      <div class="swiper-wrapper">
        <% @course.course_images.each do |image| %>
        <div class="swiper-slide">
          <%= image_tag image.variant(gravity: "Center", resize: "700x400!",
          crop: "700x400+0+0").processed %>
        </div>
        <% end %>
      </div>
        <div class="swiper-pagination"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
    </div>
    <div class="bg-white col-10 mx-auto py-2 mt-4">
      <div class="row justify-content-start col-12 mx-auto mt-4 align-items-end border-bottom pb-2">
        <div class="col-8 show-content-wrapper">
          <h3 class="text-center"><%= @course.title %></h3>
          <p class="text-muted mb-0 text-center"><%= get_address(@course.addresses)%>(<%= @course.distance%>Km)</p>
        </div>
        <div class="col-4">
          <%= link_to admin_user_path(@course.user), class:"text-secondary" do %>
            <%= image_tag @course.user.user_image.variant(gravity: "Center", resize: "50x50!", crop: "50x50+0+0").processed,
            class:"user-icon" %>
            <span class="show-user-link"><%= @course.user.name %></span>
          <% end %>
        </div>
      </div>
      <div class="col-12 col-md-11 mx-auto">
        <div class="d-flex col-12 col-sm-10 mt-2 show-table-wrapper">
          <div class="d-flex col-12 col-sm-12 col-md-6">
            <div class="table-secondary raounded p-1">おすすめ時間帯:</div>
            <div class="p-1 ml-2"><%= @course.suggest_time_i18n%></div>
          </div>
          <div class="d-flex col-12 col-sm-12 col-md-6">
            <div class="table-secondary raounded p-1">信号の有無:</div>
            <div class="p-1 ml-2"><%= @course.signal_condition_i18n%></div>
          </div>
        </div>
        <div class="d-flex col-12 col-sm-10 mt-2 show-table-wrapper">
          <div class="d-flex col-12 col-sm-12 col-md-6">
            <div class="table-secondary raounded p-1">交通量:</div>
            <div class="p-1 ml-2"><%= @course.traffic_volume_i18n%></div>
          </div>
          <div class="d-flex col-12 col-sm-12 col-md-6">
            <div class="table-secondary raounded p-1">勾配:</div>
            <div class="p-1 ml-2"><%= @course.is_slope_i18n %></div>
          </div>
        </div>
      </div>
      <div class="row mt-4 align-items-end">
      <div class="col-6  row mx-auto show-link-btn justify-content-center mb-2">
        <div  class="mr-4 text-muted">
           <i class="fas fa-running"></i>
           <%= @course.favorites.count %>走りたい
        </div>
        <div class="text-muted">
          <i class="fas fa-running"></i>
          <%= @course.finishes.count %>走った
        </div>
      </div>
        <div class="col-4 px-0 d-inline-flex justify-content-end mr-4">
          <div>
            <%= link_to '消去', admin_course_path(@course), method: :delete, class:"btn btn-danger btn-sm", 
            "data-confirm" => "本当に消去しますか?" %>
          </div>
        </div>
      </div>
    </div>
      <div id="map" class="mx-auto mt-4 col-11"></div>
      <div class="col-9 mx-auto mt-4 bg-white py-4">
        <h5 class="text-center font-weight-blod border-bottom pb-1"> - 関連ワード - </h5>
        <div class="d-flex flex-wrap mt-3">
          <% @course.entities.each do |entity| %>
            <div class="text-center px-1 ml-2">
              <span class="key_word_tag shadow-sm"><%= entity.key_word %></span>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-9 mx-auto mt-4 h5">詳細情報:</div>
      <div class="col-9 bg-white mx-auto py-3 px-2">
        <%= safe_join(@course.introduction.split("\n"), tag(:br))%>
      </div>
      <% if @course.comments.present? %>
      <div class="col-10 mx-auto mt-4">
        <%= render 'public/comments/index', course: @course %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<div id="position_info" data-json="<%= @course.positions.to_json %>"></div>
<%= javascript_pack_tag 'public/show' %>