config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as:'guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"

    resources :courses do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resource :finishes, only: [:create, :destroy]
    end
    patch 'users/withdrawal', to: 'users#withdrawal'
    resources :users, only: [:show, :update,] do
      resource :relationships, only:[:create, :destroy]
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :destroy] do
      patch 'withdrawal', to:'users#withdrawal'
    end
    resources :courses, only: [:index, :show, :destroy]
    get '/', to: 'users#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-8">
    <h5><%= obj.errors.count %>件のエラーが発生しました。</h5>
    <ul class="list-unstyled">
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-5 bg-secondary p-2 px-4">
  <div class="row py-5 border border-white">
    <div class="col-10 text-center mx-auto">
      <a href="#" class="text-white">~ Page Top ~</a>
      <div class="text-white mt-2">
        <small>
          <span>Road Record 2023 / All right reserved.</span>
        </small>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-white shadow-sm border">
  <nav class="navbar navbar-expand-md flex-wrap">
  <div class="text-center  col-6 col-sm-6 py-2  col-md-10 px-0 mx-auto">
    <%= link_to root_path, class:"aligin-bottom text-dark" do %>
      <%= image_tag 'ranner.png',size:"30x30" %>
      <strong class="h3 border-bottom border-dark">Road Record</strong>
    <% end %>
  </div>
      <button class="navbar-toggler py-2 btn btn-secondary bg-secondary" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        メニュー
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mx-auto col-lg-11 justify-content-between">
        <% if user_signed_in? %>
          <li class="mx-2">
            <%= link_to root_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-home"></i> ホーム
            <% end %>
          </li>
          <li class="mx-2">
            <%=  link_to courses_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-road"></i> コース一覧
            <% end %>
          </li>
          <li class="mx-2">
            <%=  link_to new_course_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-map-marker-alt"></i></i> コース投稿
            <% end %>
          </li>
          <li class="mx-2">
            <%=  link_to user_path(current_user) ,class: 'nav-link text-dark' do %>
              <i class="fas fa-user"></i> マイページ
            <% end %>
          </li>
          <li class="mx-2">
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
          
          <% elsif admin_signed_in? %>
          <li class="mx-2">
            <%=  link_to admin_courses_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-road"></i> コース一覧
            <% end %>
          </li>
          <li class="mx-2">
            <%=  link_to admin_users_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-users"></i></i> ユーザー一覧
            <% end %>
          </li>
          <li class="mx-2">
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li class="mx-2">
            <%= link_to root_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-home"></i> ホーム
            <% end %>
          </li>
          <li class="mx-2">
            <%=  link_to guest_sign_in_path, method: :post,  class: 'nav-link text-dark' do %>
              <i class="fas fa-user"></i> ゲストログイン
            <% end %>
          </li>
          <li class="mx-2">
            <%= link_to new_user_registration_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-user-plus"></i> 新規会員登録
            <% end %>
          </li>
          <li class="mx-2">
            <%= link_to new_user_session_path ,class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoadRecode</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-lg mx-auto">
      <%= render 'layouts/header' %>
      <main>
        <p class="notice text-success font-weight-bold"><%= notice %></p>
        <p class="alert text-danger font-weight-bold"><%= alert %></p>
        <%= yield %>
      </main>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>